name: Validate Duckie-Issues

on:
  push:
    paths:
      - 'features/**'
      - 'steps/**'
  pull_request:

jobs:
  behave-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run Duckie Quality Features
        run: behave features/
